// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
	}
}

interface CloudflareEnv extends Cloudflare.Env {
	DB: D1Database;
}
